/*!
 * \file     PARconfig.c
 * \brief    This file contains the definition of parameters configuration
 *
 *           TRONICO
 *           26, rue du bocage
 *           85660 St Philbert De Bouaine
 **/

/* ---- Includes ---- */
#include "PAR.h"
#include "PARenum.h"
/* ---- Defines ---- */

/* ---- Global variables ---- */

PAR_ConfigStr PAR_paramConfig[PAR_COUNT] =
{
    [PAR_SW_VERSION] =
    {
        .readAccessRight = PAR_ACCESSRIGHT_NO_PRIVILEDGE,
        .writeAccessRight = PAR_ACCESSRIGHT_NO_ACCESS,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = MIN_UNSIGNED32_VAL,
        .max.unsignedVal = MAX_UNSIGNED32_VAL,
        .defaultVal.unsignedVal = CST_SW_VERSION,
    },
    [PAR_FILE_VERSION] = {
        .readAccessRight = PAR_ACCESSRIGHT_NO_PRIVILEDGE,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = MIN_UNSIGNED32_VAL,
        .max.unsignedVal = MAX_UNSIGNED32_VAL,
        .defaultVal.unsignedVal = PAR_DEFAULT_VERSIONS,
    },
    [PAR_SERIAL_NUMBER] = {
        .readAccessRight = PAR_ACCESSRIGHT_NO_PRIVILEDGE,
        .writeAccessRight = PAR_ACCESSRIGHT_NO_ACCESS,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = MIN_UNSIGNED32_VAL,
        .max.unsignedVal = MAX_UNSIGNED32_VAL,
        .defaultVal.unsignedVal = PAR_DEFAULT_SERIAL_NR,
    },
    [PAR_BOOTLOADER_VERSION] = {
        .readAccessRight = PAR_ACCESSRIGHT_NO_PRIVILEDGE,
        .writeAccessRight = PAR_ACCESSRIGHT_NO_ACCESS,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = MIN_UNSIGNED32_VAL,
        .max.unsignedVal = MAX_UNSIGNED32_VAL,
        .defaultVal.unsignedVal = PAR_DEFAULT_VERSIONS,
    },
    [PAR_DF_ENS_NUMBER] = {
        .readAccessRight = PAR_ACCESSRIGHT_NO_PRIVILEDGE,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = MIN_UNSIGNED32_VAL,
        .max.unsignedVal = MAX_UNSIGNED32_VAL,
        .defaultVal.unsignedVal = PAR_DEFAULT_VERSIONS,
    },
    [PAR_DEFAULT_VERSION] = {
        .readAccessRight = PAR_ACCESSRIGHT_NO_PRIVILEDGE,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = MIN_UNSIGNED32_VAL,
        .max.unsignedVal = MIN_UNSIGNED32_VAL,
        .defaultVal.unsignedVal = PAR_FUNCTIONALITY_DISABLED,
    },
    [PAR_BOOT_FLAG] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_FUNCTIONALITY_DISABLED,
        .max.unsignedVal = PAR_FUNCTIONALITY_ENABLED,
        .defaultVal.unsignedVal = PAR_DEFAULT_BOOT_FLAG,
    },
    [PAR_COUNT_WR] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.signedVal = MAX_SIGNED32_VAL,
        .max.signedVal = MIN_SIGNED32_VAL,
        .defaultVal.signedVal = PAR_DEFAULT_COUNT_WR,
    },
    [PAR_CONTROLCAN_TIMEOUT] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.signedVal = PAR_MIN_CAN_TIMEOUT,
        .max.signedVal = PAR_MAX_CAN_TIMEOUT,
        .defaultVal.signedVal = PAR_DEFAULT_CAN_TIMEOUT,
    },
    [PAR_INTERNALCAN_TIMEOUT] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.signedVal = PAR_MIN_CAN_TIMEOUT,
        .max.signedVal = PAR_MAX_CAN_TIMEOUT,
        .defaultVal.signedVal = PAR_DEFAULT_CAN_TIMEOUT,
    },
    [PAR_CAN_BASE_TX_PERIOD] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.signedVal = PAR_MIN_CAN_TX_PERIOD,
        .max.signedVal = PAR_MAX_CAN_TX_PERIOD,
        .defaultVal.signedVal = PAR_DEFAULT_CAN_TX_PERIOD,
    },
    [PAR_COM_PWR_MEAS_FRAMES_PERIOD] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.signedVal = PAR_MIN_COM_SEND_FRAMES,
        .max.signedVal = PAR_MAX_COM_SEND_FRAMES,
        .defaultVal.signedVal = PAR_DEFAULT_COM_SEND_FRAMES,
    },
    [PAR_COM_TEMP_MEAS_FRAMES_PERIOD] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.signedVal = PAR_MIN_COM_SEND_FRAMES,
        .max.signedVal = PAR_MAX_COM_SEND_FRAMES,
        .defaultVal.signedVal = PAR_DEFAULT_COM_SEND_FRAMES,
    },
    [PAR_COM_ALERT_FRAMES_PERIOD] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.signedVal = PAR_MIN_COM_SEND_FRAMES,
        .max.signedVal = PAR_MAX_COM_SEND_FRAMES,
        .defaultVal.signedVal = PAR_DEFAULT_COM_SEND_FRAMES,
    },
    [PAR_COM_STATUS_FRAMES_PERIOD] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.signedVal = PAR_MIN_COM_SEND_FRAMES,
        .max.signedVal = PAR_MAX_COM_SEND_FRAMES,
        .defaultVal.signedVal = PAR_DEFAULT_COM_SEND_FRAMES,
    },
    [PAR_COM_INTERNAL_FRAMES_PERIOD] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.signedVal = PAR_MIN_COM_SEND_FRAMES,
        .max.signedVal = PAR_MAX_COM_SEND_FRAMES,
        .defaultVal.signedVal = PAR_DEFAULT_COM_INTERNAL_SEND_FRAMES,
    },
    [PAR_BOOST_VOLTAGE_SETPOINT] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.signedVal = PAR_MIN_BOOST_VOLTAGE_SETPOINT,
        .max.signedVal = PAR_MAX_BOOST_VOLTAGE_SETPOINT,
        .defaultVal.signedVal = PAR_DEFAULT_BOOST_VOLTAGE_SETPOINT,
    },
    [PAR_BOOST_AUTONOMOUS_END_DELTA] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.signedVal = PAR_MIN_AUTO_END_DELTA,
        .max.signedVal = PAR_MAX_AUTO_END_DELTA,
        .defaultVal.signedVal = PAR_DEFAULT_AUTO_END_DELTA,
    },
    [PAR_BOOST_POWER_SETPOINT] = { // not used for the moment reserved for later use maybe
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_SIGNED_32,
        .min.signedVal = PAR_MIN_POWER_SETPOINT,
        .max.signedVal = PAR_MAX_POWER_SETPOINT,
        .defaultVal.signedVal = PAR_DEFAULT_POWER_SETPOINT,
    },
    [PAR_BOOST_RAMP] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_SIGNED_32,
        .min.signedVal = PAR_MIN_RAMP,
        .max.signedVal = PAR_MAX_RAMP,
        .defaultVal.signedVal = PAR_DEFAULT_RAMP,
    },
    [PAR_BUCK_VOLTAGE_DEFAULT_SETPOINT] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_SIGNED_32,
        .min.signedVal = PAR_MIN_BUCK_VOLTAGE_SETPOINT,
        .max.signedVal = PAR_MAX_BUCK_VOLTAGE_SETPOINT,
        .defaultVal.signedVal = PAR_DEFAULT_BUCK_VOLTAGE_SETPOINT,
    },
    [PAR_BUCK_RAMP] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_MIN_RAMP,
        .max.unsignedVal = PAR_MAX_RAMP,
        .defaultVal.unsignedVal = PAR_DEFAULT_RAMP,
    },
    [PAR_BUCK_DEFAULT_CURRENT_LIMIT] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_MIN_BUCK_CURRENT_LIMIT,
        .max.unsignedVal = PAR_MAX_BUCK_CURRENT_LIMIT,
        .defaultVal.unsignedVal = PAR_DEFAULT_BUCK_CURRENT_LIMIT,
    },
    [PAR_BBAUX_TEMP_THRESH_GENTLEWARN] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_MIN_TEMP_THRESH,
        .max.unsignedVal = PAR_MAX_TEMP_THRESH,
        .defaultVal.unsignedVal = PAR_DEFAULT_TEMP_FIRST_THRESH ,
    },
    [PAR_BBAUX_TEMP_THRESH_URGENTWARN] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_MIN_TEMP_THRESH,
        .max.unsignedVal = PAR_MAX_TEMP_THRESH,
        .defaultVal.unsignedVal = PAR_DEFAULT_TEMP_SEC_THRESH ,
    },
    [PAR_BBAUX_TEMP_THRESH_CRITICALERR] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_NO_PRIVILEDGE,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_MIN_TEMP_THRESH,
        .max.unsignedVal = PAR_MAX_TEMP_THRESH,
        .defaultVal.unsignedVal = PAR_DEFAULT_TEMP_THIRD_THRESH ,
    },
    [PAR_POWERCORE_TEMP_THRESH_GENTLEWARN] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_MIN_TEMP_THRESH_POWERCORE,
        .max.unsignedVal = PAR_MAX_TEMP_THRESH_POWERCORE,
        .defaultVal.unsignedVal = PAR_DEFAULT_TEMP_FIRST_THRESH_POWERCORE,
    },
    [PAR_POWERCORE_TEMP_THRESH_URGENTWARN] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_MIN_TEMP_THRESH_POWERCORE,
        .max.unsignedVal = PAR_MAX_TEMP_THRESH_POWERCORE,
        .defaultVal.unsignedVal = PAR_DEFAULT_TEMP_SEC_THRESH_POWERCORE,
    },
    [PAR_POWERCORE_TEMP_THRESH_CRITICALERR] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_MIN_TEMP_THRESH_POWERCORE,
        .max.unsignedVal = PAR_MAX_TEMP_THRESH_POWERCORE,
        .defaultVal.unsignedVal = PAR_DEFAULT_TEMP_THIRD_THRESH_POWERCORE,
    },
    [PAR_WARNINGS_MASK] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_MIN_ERRORSMASK,
        .max.unsignedVal = PAR_MAX_ERRORSMASK,
        .defaultVal.unsignedVal = PAR_DEFAULT_ERRORSMASK ,
    },
    [PAR_OPERATING_ERRORS_MASK] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_MIN_ERRORSMASK,
        .max.unsignedVal = PAR_MAX_ERRORSMASK,
        .defaultVal.unsignedVal = PAR_DEFAULT_ERRORSMASK,
    },
    [PAR_CRITICAL_ERRORS_MASK] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_MIN_ERRORSMASK,
        .max.unsignedVal = PAR_MAX_ERRORSMASK,
        .defaultVal.unsignedVal = PAR_DEFAULT_ERRORSMASK,
    },
    [PAR_CALIBRATION_A_VLV] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_SIGNED_32,
        .min.signedVal = PAR_MIN_CALIBRATION,
        .max.signedVal = PAR_MAX_CALIBRATION,
        .defaultVal.unsignedVal = PAR_DEFAULT_CALIBRATION_A_VLV,
    },
    [PAR_CALIBRATION_B_VLV] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_SIGNED_32,
        .min.signedVal = PAR_MIN_CALIBRATION,
        .max.signedVal = PAR_MAX_CALIBRATION,
        .defaultVal.unsignedVal = PAR_DEFAULT_CALIBRATION_B_VLV,
    },
    [PAR_CALIBRATION_A_IHV] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_SIGNED_32,
        .min.signedVal = PAR_MIN_CALIBRATION,
        .max.signedVal = PAR_MAX_CALIBRATION,
        .defaultVal.unsignedVal = PAR_DEFAULT_CALIBRATION_A_IHV,
    },
    [PAR_CALIBRATION_B_IHV] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_SIGNED_32,
        .min.signedVal = PAR_MIN_CALIBRATION,
        .max.signedVal = PAR_MAX_CALIBRATION,
        .defaultVal.unsignedVal = PAR_DEFAULT_CALIBRATION_B_IHV,
    },
    [PAR_CALIBRATION_A_VHV] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_SIGNED_32,
        .min.signedVal = PAR_MIN_CALIBRATION,
        .max.signedVal = PAR_MAX_CALIBRATION,
        .defaultVal.unsignedVal = PAR_DEFAULT_CALIBRATION_A_VHV,
    },
    [PAR_CALIBRATION_B_VHV] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_SIGNED_32,
        .min.signedVal = PAR_MIN_CALIBRATION,
        .max.signedVal = PAR_MAX_CALIBRATION,
        .defaultVal.unsignedVal = PAR_DEFAULT_CALIBRATION_B_VHV,
    },
    [PAR_CALIBRATION_A_T1] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_SIGNED_32,
        .min.signedVal = PAR_MIN_CALIBRATION,
        .max.signedVal = PAR_MAX_CALIBRATION,
        .defaultVal.unsignedVal = PAR_DEFAULT_CALIBRATION_A_T1,
    },
    [PAR_CALIBRATION_B_T1] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_SIGNED_32,
        .min.signedVal = PAR_MIN_CALIBRATION,
        .max.signedVal = PAR_MAX_CALIBRATION,
        .defaultVal.unsignedVal = PAR_DEFAULT_CALIBRATION_B_T1,
    },
    [PAR_HV_DIOD_BYPASS_START_CONDITION] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_MIN_DIOD_BYPASS_START,
        .max.unsignedVal = PAR_MAX_DIOD_BYPASS_START,
        .defaultVal.unsignedVal = PAR_DEFAULT_DIOD_BYPASS_START ,
    },
    [PAR_HV_DIOD_BYPASS_STOP_CONDITION] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_MIN_DIOD_BYPASS_STOP,
        .max.unsignedVal = PAR_MAX_DIOD_BYPASS_STOP,
        .defaultVal.unsignedVal = PAR_DEFAULT_DIOD_BYPASS_STOP ,
    },
    [PAR_LV_PRECHARGE_START_CONDITION] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_MIN_PRECHARGE_START,
        .max.unsignedVal = PAR_MAX_PRECHARGE_START,
        .defaultVal.unsignedVal = PAR_DEFAULT_PRECHARGE_START ,
    },
    [PAR_LV_PRECHARGE_STOP_DELTA] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_MIN_PRECHARGE_STOP,
        .max.unsignedVal = PAR_MAX_PRECHARGE_STOP,
        .defaultVal.unsignedVal = PAR_DEFAULT_PRECHARGE_STOP,
    },
    [PAR_POWERCORE_BOOST_MAX_POWER] = { // not used for the moment reserved for later use
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_MIN_POWERCORE_POWER,
        .max.unsignedVal = PAR_MAX_POWERCORE_POWER,
        .defaultVal.unsignedVal = PAR_DEFAULT_POWERCORE_POWER,
    },
    [PAR_POWERCORE_BUCK_MAX_POWER] = { // not used for the moment reserved for later use
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_MIN_POWERCORE_POWER,
        .max.unsignedVal = PAR_MAX_POWERCORE_POWER,
        .defaultVal.unsignedVal = PAR_DEFAULT_POWERCORE_POWER,
    },
    [PAR_HVCOUPLER_RELAY_TEST_CONDITION] = { // not used for the moment reserved for later use
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_MIN_HVCOUPLER_RELAY_TEST,
        .max.unsignedVal = PAR_MAX_HVCOUPLER_RELAY_TEST,
        .defaultVal.unsignedVal = PAR_DEFAULT_HVCOUPLER_RELAY_TEST,
    },
    [PAR_LVPRECHARGE_RELAY_TEST_CONDITION] = { // not used for the moment reserved for later use
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_MIN_LVPRECHARGE_RELAY_TEST,
        .max.unsignedVal = PAR_MAX_LVPRECHARGE_RELAY_TEST,
        .defaultVal.unsignedVal = PAR_DEFAULT_LVPRECHARGE_RELAY_TEST,
    },
    [PAR_HVRELAY_STEADY_FREQUENCY] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_MIN_STEADY_FREQUENCY,
        .max.unsignedVal = PAR_MAX_STEADY_FREQUENCY,
        .defaultVal.unsignedVal = PAR_DEFAULT_STEADY_FREQUENCY,
    },
    [PAR_LVRELAY_STEADY_FREQUENCY] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_MIN_STEADY_FREQUENCY,
        .max.unsignedVal = PAR_MAX_STEADY_FREQUENCY,
        .defaultVal.unsignedVal = PAR_DEFAULT_STEADY_FREQUENCY,
    },
    [PAR_ACTIVITY_EXTENSION_TIMER] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = MIN_UNSIGNED32_VAL,
        .max.unsignedVal = MAX_UNSIGNED32_VAL,
        .defaultVal.unsignedVal = PAR_DEFAULT_ACTIVITY_EXTENSION_TIMER,
    },
    [PAR_VOLTAGEMEAS_CONFIRMATION_TIME] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = MIN_UNSIGNED8_VAL,
        .max.unsignedVal = MAX_UNSIGNED8_VAL,
        .defaultVal.unsignedVal = PAR_CONFIRMATION_TIME_DEFAULT_VALUE,
    },
    [PAR_CURRENTMEAS_CONFIRMATION_TIME] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = MIN_UNSIGNED8_VAL,
        .max.unsignedVal = MAX_UNSIGNED8_VAL,
        .defaultVal.unsignedVal = PAR_CONFIRMATION_TIME_DEFAULT_VALUE,
    },
    [PAR_TEMPMEAS_CONFIRMATION_TIME] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = MIN_UNSIGNED8_VAL,
        .max.unsignedVal = MAX_UNSIGNED8_VAL,
        .defaultVal.unsignedVal = PAR_CONFIRMATION_TIME_DEFAULT_VALUE,
    },
    [PAR_BUCK_CURRENTSOURCE_MAXDURATION] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = MIN_UNSIGNED8_VAL,
        .max.unsignedVal = MAX_UNSIGNED8_VAL,
        .defaultVal.unsignedVal = PAR_BUCK_CURRENTSOURCE_MAXDURATION_DEFAULT_VALUE,
    },

    [PAR_BUCK_CURRENTSOURCE_MINVOLTAGE] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_MIN_BUCK_CURRENTSOURCE_MINVOLTAGE,
        .max.unsignedVal = PAR_MAX_BUCK_CURRENTSOURCE_MINVOLTAGE,
        .defaultVal.unsignedVal = PAR_DEFAULT_BUCK_CURRENTSOURCE_MINVOLTAGE,
    },
    [PAR_BBAUX_BUCK_HV_OVERCURRENT_MAX] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_DEFAULT_BBAUX_BUCK_HV_OVERCURRENT_MIN,
        .max.unsignedVal = PAR_DEFAULT_BBAUX_BUCK_HV_OVERCURRENT_MAX,
        .defaultVal.unsignedVal = PAR_DEFAULT_BBAUX_BUCK_HV_OVERCURRENT,
    },
    [PAR_BBAUX_BOOST_HV_OVERCURRENT_MAX] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_DEFAULT_BBAUX_BOOST_HV_OVERCURRENT_MIN,
        .max.unsignedVal = PAR_DEFAULT_BBAUX_BOOST_HV_OVERCURRENT_MAX,
        .defaultVal.unsignedVal = PAR_DEFAULT_BBAUX_BOOST_HV_OVERCURRENT,
    },
    [PAR_COMETI_BUCK_HV_OVERCURRENT_MAX] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_DEFAULT_COMETI_BUCK_HV_OVERCURRENT_MIN,
        .max.unsignedVal = PAR_DEFAULT_COMETI_BUCK_HV_OVERCURRENT_MAX,
        .defaultVal.unsignedVal = PAR_DEFAULT_COMETI_BUCK_HV_OVERCURRENT,
    },
    [PAR_COMETI_BOOST_HV_OVERCURRENT_MAX] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_DEFAULT_COMETI_BOOST_HV_OVERCURRENT_MIN,
        .max.unsignedVal = PAR_DEFAULT_COMETI_BOOST_HV_OVERCURRENT_MAX,
        .defaultVal.unsignedVal = PAR_DEFAULT_COMETI_BOOST_HV_OVERCURRENT,
    },
    [PAR_COMETI_BUCK_LV_OVERCURRENT_MAX] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_DEFAULT_COMETI_BUCK_LV_OVERCURRENT_MIN,
        .max.unsignedVal = PAR_DEFAULT_COMETI_BUCK_LV_OVERCURRENT_MAX,
        .defaultVal.unsignedVal = PAR_DEFAULT_COMETI_BUCK_LV_OVERCURRENT,
    },
    [PAR_COMETI_BOOST_LV_OVERCURRENT_MAX] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_DEFAULT_COMETI_BOOST_LV_OVERCURRENT_MIN,
        .max.unsignedVal = PAR_DEFAULT_COMETI_BOOST_LV_OVERCURRENT_MAX,
        .defaultVal.unsignedVal = PAR_DEFAULT_COMETI_BOOST_LV_OVERCURRENT,
    },
    [PAR_BBAUX_BUCK_HV_OVERVOLTAGE_MAX] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_DEFAULT_BUCK_HV_OVERVOLTAGE_MIN,
        .max.unsignedVal = PAR_DEFAULT_BUCK_HV_OVERVOLTAGE_MAX,
        .defaultVal.unsignedVal = PAR_DEFAULT_BUCK_HV_OVERVOLTAGE,
    },
    [PAR_BBAUX_BOOST_HV_OVERVOLTAGE_MAX] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_DEFAULT_BOOST_HV_OVERVOLTAGE_MIN,
        .max.unsignedVal = PAR_DEFAULT_BOOST_HV_OVERVOLTAGE_MAX,
        .defaultVal.unsignedVal = PAR_DEFAULT_BOOST_HV_OVERVOLTAGE,
    },
    [PAR_BBAUX_BUCK_LV_OVERVOLTAGE_MAX] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_DEFAULT_LV_OVERVOLTAGE_MIN,
        .max.unsignedVal = PAR_DEFAULT_LV_OVERVOLTAGE_MAX,
        .defaultVal.unsignedVal = PAR_DEFAULT_LV_OVERVOLTAGE,
    },
    [PAR_BBAUX_BOOST_LV_OVERVOLTAGE_MAX] = {
        .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
        .type = PAR_TYPE_UNSIGNED_32,
        .min.unsignedVal = PAR_DEFAULT_LV_OVERVOLTAGE_MIN,
        .max.unsignedVal = PAR_DEFAULT_LV_OVERVOLTAGE_MAX,
        .defaultVal.unsignedVal = PAR_DEFAULT_LV_OVERVOLTAGE,
    },
    [PAR_BOOST_CURRENT_LIMIT] = {
            .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
            .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
            .type = PAR_TYPE_UNSIGNED_32,
            .min.unsignedVal = PAR_MIN_BOOST_CURRENT_LIMIT,
            .max.unsignedVal = PAR_MAX_BOOST_CURRENT_LIMIT,
            .defaultVal.unsignedVal = PAR_DEFAULT_BOOST_CURRENT_LIMIT,
        },
    [PAR_LV_PRECHARGE_DURATION_MAX] = {
            .readAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
            .writeAccessRight = PAR_ACCESSRIGHT_SUPERUSER,
            .type = PAR_TYPE_UNSIGNED_32,
            .min.unsignedVal = MIN_UNSIGNED32_VAL,
            .max.unsignedVal = MAX_UNSIGNED32_VAL,
            .defaultVal.unsignedVal = PAR_LV_PRECHARGE_DURATION_MAX_DEFAULT,
        }
};


/* ---- External functions ---- */

/* ---- Static variables ---- */

/* ---- Static functions ---- */
