/*!
 * \file     PAR_DefaultValues.h
 * \brief    Brief description of file content
 *
 *           TRONICO
 *           26, rue du bocage
 *           85660 St Philbert De Bouaine
 **/

#ifndef FILE_PARDEF_H
#define FILE_PARDEF_H

/* ---- Includes ---- */
#include "TYPedef.h"
#include "CST.h"

/* ---- Defines ---- */

/*------------------------------*/
/* Default values of parameters */
/*------------------------------*/
//TODO : Verify Compliance with parameters.xls

#define PAR_DEFAULT_UNSIGNED_ZERO   0U
// Default Serial Number
#define PAR_DEFAULT_SERIAL_NR              0x5A5A5A5A

// Default Setpoint step values
#define PAR_DEFAULT_STARTUP_TIME    30U // 0.1s
#define PAR_DEFAULT_STOP_TIME       10U // 0.1s
#define PAR_DEFAULT_CHANGE_STEP     100U // 0.1 V/A or 1W /100ms

// CAN communication default values
#define PAR_DEFAULT_CAN_ADDR 0x00U
#define PAR_DEFAULT_CAN_TIMEOUT    10U // 0.1s
#define PAR_DEFAULT_CAN_BITRATE    0x00U // 500Kbps no FD (check the MCAL)
#define PAR_DEFAULT_CAN_TX_PERIOD   1U // 1 * 10ms
#define PAR_DEFAULT_COM_SEND_FRAMES 5U // 5 * PAR_CAN_TX_PERIOD
#define PAR_DEFAULT_COM_INTERNAL_SEND_FRAMES 10U // 5 * PAR_CAN_TX_PERIOD

// Voltage and current measures default param value
#define PAR_DEFAULT_GAIN        1U
#define PAR_DEFAULT_OFFSET      0U

// Regulation mode and type default values
#define PAR_DEFAULT_REG_MODE_ENABLED  1U
#define PAR_DEFAULT_REG_MODE          1U
#define PAR_DEFAULT_REG_TYPE_ENABLED  8U
#define PAR_DEFAULT_REG_TYPE          4U

#define PAR_MIN_BOOST_VOLTAGE_SETPOINT    380U
#define PAR_MAX_BOOST_VOLTAGE_SETPOINT    420U
#define PAR_DEFAULT_BOOST_VOLTAGE_SETPOINT    400U

#define PAR_MIN_AUTO_END_DELTA      0U
#define PAR_MAX_AUTO_END_DELTA      100U
#define PAR_DEFAULT_AUTO_END_DELTA      50U

#define PAR_MIN_POWER_SETPOINT      2U
#define PAR_MAX_POWER_SETPOINT      24U
#define PAR_DEFAULT_POWER_SETPOINT      24U

#define PAR_MIN_BUCK_VOLTAGE_SETPOINT      24U
#define PAR_MAX_BUCK_VOLTAGE_SETPOINT      28U
#define PAR_DEFAULT_BUCK_VOLTAGE_SETPOINT      28U

#define PAR_MIN_RAMP      1U
#define PAR_MAX_RAMP      400U
#define PAR_DEFAULT_RAMP      40U

#define PAR_MIN_BUCK_CURRENT_LIMIT      50U
#define PAR_MAX_BUCK_CURRENT_LIMIT      357U
#define PAR_DEFAULT_BUCK_CURRENT_LIMIT      357U

#define PAR_MIN_BOOST_CURRENT_LIMIT      30U
#define PAR_MAX_BOOST_CURRENT_LIMIT      30U
#define PAR_DEFAULT_BOOST_CURRENT_LIMIT      30U

#define PAR_MIN_TEMP_THRESH      0U
#define PAR_MAX_TEMP_THRESH      1000U
#define PAR_DEFAULT_TEMP_FIRST_THRESH      600U
#define PAR_DEFAULT_TEMP_SEC_THRESH      700U
#define PAR_DEFAULT_TEMP_THIRD_THRESH      800U

#define PAR_MIN_TEMP_THRESH_POWERCORE      0U
#define PAR_MAX_TEMP_THRESH_POWERCORE      100U
#define PAR_DEFAULT_TEMP_FIRST_THRESH_POWERCORE      60U
#define PAR_DEFAULT_TEMP_SEC_THRESH_POWERCORE     70U
#define PAR_DEFAULT_TEMP_THIRD_THRESH_POWERCORE      80U

#define PAR_MIN_ERRORSMASK      0x00000000
#define PAR_MAX_ERRORSMASK      0xFFFFFFFF
#define PAR_DEFAULT_ERRORSMASK      0xFFFFFFFF

#define PAR_MIN_CALIBRATION      MIN_SIGNED32_VAL
#define PAR_MAX_CALIBRATION      MAX_SIGNED32_VAL
#define PAR_DEFAULT_CALIBRATION_A_VLV      13U
#define PAR_DEFAULT_CALIBRATION_B_VLV      196U

#define PAR_DEFAULT_CALIBRATION_A_VHV      139U
#define PAR_DEFAULT_CALIBRATION_B_VHV      361U

#define PAR_DEFAULT_CALIBRATION_A_IHV      386U
#define PAR_DEFAULT_CALIBRATION_B_IHV       4293396626U

#define PAR_DEFAULT_CALIBRATION_A_T1      26U
#define PAR_DEFAULT_CALIBRATION_B_T1      4294951582U

#define PAR_MIN_DIOD_BYPASS_START      4400U
#define PAR_MAX_DIOD_BYPASS_START      4600U
#define PAR_DEFAULT_DIOD_BYPASS_START      4500U

#define PAR_MIN_DIOD_BYPASS_STOP      3600U
#define PAR_MAX_DIOD_BYPASS_STOP      3900U
#define PAR_DEFAULT_DIOD_BYPASS_STOP      3750U

#define PAR_MIN_PRECHARGE_START      240U
#define PAR_MAX_PRECHARGE_START      2550U
#define PAR_DEFAULT_PRECHARGE_START      240U

#define PAR_MIN_PRECHARGE_STOP      0U
#define PAR_MAX_PRECHARGE_STOP      50U
#define PAR_DEFAULT_PRECHARGE_STOP      20U

#define PAR_MIN_POWERCORE_POWER      2U
#define PAR_MAX_POWERCORE_POWER      12U
#define PAR_DEFAULT_POWERCORE_POWER      12U

#define PAR_MIN_HVCOUPLER_RELAY_TEST      40U
#define PAR_MAX_HVCOUPLER_RELAY_TEST      60U
#define PAR_DEFAULT_HVCOUPLER_RELAY_TEST     50U

#define PAR_MIN_LVPRECHARGE_RELAY_TEST      22U
#define PAR_MAX_LVPRECHARGE_RELAY_TEST      26U
#define PAR_DEFAULT_LVPRECHARGE_RELAY_TEST     24U

#define PAR_MIN_STEADY_FREQUENCY      0U
#define PAR_MAX_STEADY_FREQUENCY      0xFFFFFFFF
#define PAR_DEFAULT_STEADY_FREQUENCY     500U

#define PAR_DEFAULT_ACTIVITY_EXTENSION_TIMER    50U

#define PAR_CONFIRMATION_TIME_DEFAULT_VALUE 50U

#define PAR_BUCK_CURRENTSOURCE_MAXDURATION_DEFAULT_VALUE 200U

#define PAR_MIN_BUCK_CURRENTSOURCE_MINVOLTAGE      22U
#define PAR_MAX_BUCK_CURRENTSOURCE_MINVOLTAGE      26U
#define PAR_DEFAULT_BUCK_CURRENTSOURCE_MINVOLTAGE     24U

// Default Versions value
#define PAR_DEFAULT_VERSIONS       0xFFFFFFFF

// Temp thresholds
#define PAR_DEFAULT_TEMP_DELTA          5U
#define PAR_DEFAULT_TEMP_THRESH_REDUC   65U
#define PAR_DEFAULT_TEMP_THRESH_STOP    80U

// Voltage thresholds
#define PAR_DEFAULT_VBUS2_MAX_CRITICAL 48000U //mv
#define PAR_DEFAULT_ABSOLUTE_VBUS2_MAX 48000U
#define PAR_DEFAULT_ABSOLUTE_VBUS2_MIN 18000U
#define PAR_DEFAULT_VBUS2_MAX 36000U
#define PAR_DEFAULT_VBUS2_MIN 18000U

#define PAR_DEFAULT_VBUS1_MAX_CRITICAL 950000U
#define PAR_DEFAULT_ABSOLUTE_VBUS1_MAX 950000U
#define PAR_DEFAULT_ABSOLUTE_VBUS1_MIN 200000U
#define PAR_DEFAULT_VBUS1_MAX 900000U
#define PAR_DEFAULT_VBUS1_MIN 200000U


#define PAR_DEFAULT_COMETI_BUCK_HV_OVERCURRENT     20U
#define PAR_DEFAULT_COMETI_BUCK_HV_OVERCURRENT_MIN     15U
#define PAR_DEFAULT_COMETI_BUCK_HV_OVERCURRENT_MAX     35U

#define PAR_DEFAULT_COMETI_BOOST_HV_OVERCURRENT     35U
#define PAR_DEFAULT_COMETI_BOOST_HV_OVERCURRENT_MIN     20U
#define PAR_DEFAULT_COMETI_BOOST_HV_OVERCURRENT_MAX     50U

#define PAR_DEFAULT_COMETI_BUCK_LV_OVERCURRENT     250U
#define PAR_DEFAULT_COMETI_BUCK_LV_OVERCURRENT_MIN     220U
#define PAR_DEFAULT_COMETI_BUCK_LV_OVERCURRENT_MAX     280U

#define PAR_DEFAULT_COMETI_BOOST_LV_OVERCURRENT     450U
#define PAR_DEFAULT_COMETI_BOOST_LV_OVERCURRENT_MIN     420U
#define PAR_DEFAULT_COMETI_BOOST_LV_OVERCURRENT_MAX     480U

#define PAR_DEFAULT_BBAUX_BUCK_HV_OVERCURRENT     3000U
#define PAR_DEFAULT_BBAUX_BUCK_HV_OVERCURRENT_MIN     2700U
#define PAR_DEFAULT_BBAUX_BUCK_HV_OVERCURRENT_MAX     3300U

#define PAR_DEFAULT_BBAUX_BOOST_HV_OVERCURRENT     3000U
#define PAR_DEFAULT_BBAUX_BOOST_HV_OVERCURRENT_MIN     3000U
#define PAR_DEFAULT_BBAUX_BOOST_HV_OVERCURRENT_MAX     4000U

#define PAR_DEFAULT_BUCK_HV_OVERVOLTAGE       8000U
#define PAR_DEFAULT_BUCK_HV_OVERVOLTAGE_MIN       2000U
#define PAR_DEFAULT_BUCK_HV_OVERVOLTAGE_MAX       8000U

#define PAR_DEFAULT_BOOST_HV_OVERVOLTAGE      4500U
#define PAR_DEFAULT_BOOST_HV_OVERVOLTAGE_MIN      4400U
#define PAR_DEFAULT_BOOST_HV_OVERVOLTAGE_MAX      4600U

#define PAR_DEFAULT_LV_OVERVOLTAGE       310U
#define PAR_DEFAULT_LV_OVERVOLTAGE_MIN       280U
#define PAR_DEFAULT_LV_OVERVOLTAGE_MAX       320U

#define PAR_LV_PRECHARGE_DURATION_MAX_DEFAULT   1000U

#define PAR_DEFAULT_BOOT_FLAG       0U
#define PAR_DEFAULT_COUNT_WR        0U

// Generic min and max for signed
#define MIN_SIGNED32_VAL            INT32_MIN
#define MAX_SIGNED32_VAL            INT32_MAX

// Generic min and max for unsigned
#define MIN_UNSIGNED8_VAL          0U
#define MAX_UNSIGNED8_VAL          UINT8_MAX
#define MIN_UNSIGNED16_VAL          0U
#define MAX_UNSIGNED16_VAL          UINT16_MAX
#define MIN_UNSIGNED32_VAL          0U
#define MAX_UNSIGNED32_VAL          UINT32_MAX
#define MAX_BOOL_VAL                1U

// Generic min and max for Gain and Offset
#define PAR_MIN_GAIN                0U
#define PAR_MAX_GAIN                MAX_SIGNED32_VAL
#define PAR_MIN_OFFSET              MIN_SIGNED32_VAL
#define PAR_MAX_OFFSET              MAX_SIGNED32_VAL

// Generic min and max for boolean
#define PAR_FUNCTIONALITY_ENABLED   1U
#define PAR_FUNCTIONALITY_DISABLED  0U

// Min and max for CAN communication
#define PAR_MIN_CAN_TIMEOUT 0U
#define PAR_MAX_CAN_TIMEOUT 100U
#define PAR_MIN_CAN_TX_PERIOD   1U
#define PAR_MAX_CAN_TX_PERIOD   100U
#define PAR_MIN_COM_SEND_FRAMES 0U
#define PAR_MAX_COM_SEND_FRAMES 100U // 1 * PAR_CAN_TX_PERIOD

// CAN bitrate
#define PAR_MIN_CAN_BITRATE    0U
#define PAR_MAX_CAN_BITRATE    15U


/* ---- Global variables ---- */

/* ---- Global functions ---- */

#endif /* FILE_PAR_DEFAULTVALUES_H */
