################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../RTD/src/CDD_Crc.c \
../RTD/src/CDD_Mcl.c \
../RTD/src/CDD_Mcl_Ipw.c \
../RTD/src/CDD_Rm.c \
../RTD/src/CDD_Rm_Ipw.c \
../RTD/src/Can.c \
../RTD/src/Can_Ipw.c \
../RTD/src/Can_Irq.c \
../RTD/src/Clock_Ip.c \
../RTD/src/Clock_Ip_Data.c \
../RTD/src/Clock_Ip_Divider.c \
../RTD/src/Clock_Ip_DividerTrigger.c \
../RTD/src/Clock_Ip_ExtOsc.c \
../RTD/src/Clock_Ip_FracDiv.c \
../RTD/src/Clock_Ip_Frequency.c \
../RTD/src/Clock_Ip_Gate.c \
../RTD/src/Clock_Ip_IntOsc.c \
../RTD/src/Clock_Ip_Irq.c \
../RTD/src/Clock_Ip_Monitor.c \
../RTD/src/Clock_Ip_Pll.c \
../RTD/src/Clock_Ip_ProgFreqSwitch.c \
../RTD/src/Clock_Ip_Selector.c \
../RTD/src/Clock_Ip_Specific.c \
../RTD/src/Cmp_Ip.c \
../RTD/src/Crc_Ip.c \
../RTD/src/Crc_Ip_Hardware.c \
../RTD/src/Crc_Ip_Lookup_Tables.c \
../RTD/src/Crc_Ip_Software.c \
../RTD/src/CryIf.c \
../RTD/src/Crypto.c \
../RTD/src/Crypto_ASRExtension.c \
../RTD/src/Crypto_Ipw.c \
../RTD/src/Crypto_KeyManagement.c \
../RTD/src/Crypto_Util.c \
../RTD/src/Csec_Ip.c \
../RTD/src/Csec_Ip_Irq.c \
../RTD/src/Det.c \
../RTD/src/Det_stub.c \
../RTD/src/Dio.c \
../RTD/src/Dio_Ipw.c \
../RTD/src/Dma_Ip.c \
../RTD/src/Dma_Ip_Driver_State.c \
../RTD/src/Dma_Ip_Hw_Access.c \
../RTD/src/Dma_Ip_Irq.c \
../RTD/src/Dma_Ip_Multicore.c \
../RTD/src/EcuM.c \
../RTD/src/FlexCAN_Ip.c \
../RTD/src/FlexCAN_Ip_HwAccess.c \
../RTD/src/FlexCAN_Ip_Irq.c \
../RTD/src/Flexio_Mcl_Ip.c \
../RTD/src/Flexio_Mcl_Ip_HwAccess.c \
../RTD/src/Flexio_Mcl_Ip_Irq.c \
../RTD/src/Flexio_Pwm_Ip.c \
../RTD/src/Flexio_Pwm_Ip_Irq.c \
../RTD/src/Flexio_Spi_Ip.c \
../RTD/src/Flexio_Spi_Ip_Irq.c \
../RTD/src/Fls.c \
../RTD/src/Fls_IPW.c \
../RTD/src/Ftfc_Fls_Ip.c \
../RTD/src/Ftfc_Fls_Ip_Ac.c \
../RTD/src/Ftm_Gpt_Ip.c \
../RTD/src/Ftm_Icu_Ip.c \
../RTD/src/Ftm_Icu_Ip_Irq.c \
../RTD/src/Ftm_Mcl_Ip.c \
../RTD/src/Ftm_Pwm_Ip.c \
../RTD/src/Ftm_Pwm_Ip_Irq.c \
../RTD/src/Gpio_Dio_Ip.c \
../RTD/src/Gpt.c \
../RTD/src/Gpt_Ipw.c \
../RTD/src/Icu.c \
../RTD/src/Icu_Ipw.c \
../RTD/src/IntCtrl_Ip.c \
../RTD/src/LPit_Gpt_Ip.c \
../RTD/src/Lpit_Icu_Ip.c \
../RTD/src/Lpit_Icu_Ip_Irq.c \
../RTD/src/Lpspi_Ip.c \
../RTD/src/Lpspi_Ip_Irq.c \
../RTD/src/Lptmr_Gpt_Ip.c \
../RTD/src/Lptmr_Icu_Ip.c \
../RTD/src/Lptmr_Icu_Ip_Irq.c \
../RTD/src/Mcu.c \
../RTD/src/Mcu_Dem_Wrapper.c \
../RTD/src/Mcu_Ipw.c \
../RTD/src/Mcu_Ipw_Irq.c \
../RTD/src/Mpu_Ip.c \
../RTD/src/OsIf_Interrupts.c \
../RTD/src/OsIf_Timer.c \
../RTD/src/OsIf_Timer_System.c \
../RTD/src/OsIf_Timer_System_Internal_Systick.c \
../RTD/src/Os_counter_api.c \
../RTD/src/Os_multicore.c \
../RTD/src/Platform.c \
../RTD/src/Platform_Ipw.c \
../RTD/src/Port.c \
../RTD/src/Port_Ci_Icu_Ip.c \
../RTD/src/Port_Ci_Icu_Ip_Irq.c \
../RTD/src/Port_Ci_Port_Ip.c \
../RTD/src/Port_Ipw.c \
../RTD/src/Power_Ip.c \
../RTD/src/Power_Ip_CortexM4.c \
../RTD/src/Power_Ip_PMC.c \
../RTD/src/Power_Ip_PMC_Irq.c \
../RTD/src/Power_Ip_Private.c \
../RTD/src/Power_Ip_RCM.c \
../RTD/src/Power_Ip_RCM_Irq.c \
../RTD/src/Power_Ip_SIM.c \
../RTD/src/Power_Ip_SMC.c \
../RTD/src/Pwm.c \
../RTD/src/Pwm_Ipw.c \
../RTD/src/Pwm_Ipw_Notif.c \
../RTD/src/Qspi_Ip.c \
../RTD/src/Qspi_Ip_Controller.c \
../RTD/src/Qspi_Ip_Sfdp.c \
../RTD/src/Ram_Ip.c \
../RTD/src/SRtc_Ip.c \
../RTD/src/SchM_Can.c \
../RTD/src/SchM_Crc.c \
../RTD/src/SchM_Crypto.c \
../RTD/src/SchM_Dio.c \
../RTD/src/SchM_Fls.c \
../RTD/src/SchM_Gpt.c \
../RTD/src/SchM_Icu.c \
../RTD/src/SchM_Mcl.c \
../RTD/src/SchM_Mcu.c \
../RTD/src/SchM_Port.c \
../RTD/src/SchM_Pwm.c \
../RTD/src/SchM_Rm.c \
../RTD/src/SchM_Spi.c \
../RTD/src/SchM_Wdg.c \
../RTD/src/Spi.c \
../RTD/src/Spi_Ipw.c \
../RTD/src/System_Ip.c \
../RTD/src/Trgmux_Ip.c \
../RTD/src/Trgmux_Ip_HwAcc.c \
../RTD/src/WdgIf.c \
../RTD/src/Wdg_43_Instance0.c \
../RTD/src/Wdg_Channel.c \
../RTD/src/Wdg_Ipw.c \
../RTD/src/Wdg_Ipw_Irq.c \
../RTD/src/Wdog_Ip.c 

OBJS += \
./RTD/src/CDD_Crc.o \
./RTD/src/CDD_Mcl.o \
./RTD/src/CDD_Mcl_Ipw.o \
./RTD/src/CDD_Rm.o \
./RTD/src/CDD_Rm_Ipw.o \
./RTD/src/Can.o \
./RTD/src/Can_Ipw.o \
./RTD/src/Can_Irq.o \
./RTD/src/Clock_Ip.o \
./RTD/src/Clock_Ip_Data.o \
./RTD/src/Clock_Ip_Divider.o \
./RTD/src/Clock_Ip_DividerTrigger.o \
./RTD/src/Clock_Ip_ExtOsc.o \
./RTD/src/Clock_Ip_FracDiv.o \
./RTD/src/Clock_Ip_Frequency.o \
./RTD/src/Clock_Ip_Gate.o \
./RTD/src/Clock_Ip_IntOsc.o \
./RTD/src/Clock_Ip_Irq.o \
./RTD/src/Clock_Ip_Monitor.o \
./RTD/src/Clock_Ip_Pll.o \
./RTD/src/Clock_Ip_ProgFreqSwitch.o \
./RTD/src/Clock_Ip_Selector.o \
./RTD/src/Clock_Ip_Specific.o \
./RTD/src/Cmp_Ip.o \
./RTD/src/Crc_Ip.o \
./RTD/src/Crc_Ip_Hardware.o \
./RTD/src/Crc_Ip_Lookup_Tables.o \
./RTD/src/Crc_Ip_Software.o \
./RTD/src/CryIf.o \
./RTD/src/Crypto.o \
./RTD/src/Crypto_ASRExtension.o \
./RTD/src/Crypto_Ipw.o \
./RTD/src/Crypto_KeyManagement.o \
./RTD/src/Crypto_Util.o \
./RTD/src/Csec_Ip.o \
./RTD/src/Csec_Ip_Irq.o \
./RTD/src/Det.o \
./RTD/src/Det_stub.o \
./RTD/src/Dio.o \
./RTD/src/Dio_Ipw.o \
./RTD/src/Dma_Ip.o \
./RTD/src/Dma_Ip_Driver_State.o \
./RTD/src/Dma_Ip_Hw_Access.o \
./RTD/src/Dma_Ip_Irq.o \
./RTD/src/Dma_Ip_Multicore.o \
./RTD/src/EcuM.o \
./RTD/src/FlexCAN_Ip.o \
./RTD/src/FlexCAN_Ip_HwAccess.o \
./RTD/src/FlexCAN_Ip_Irq.o \
./RTD/src/Flexio_Mcl_Ip.o \
./RTD/src/Flexio_Mcl_Ip_HwAccess.o \
./RTD/src/Flexio_Mcl_Ip_Irq.o \
./RTD/src/Flexio_Pwm_Ip.o \
./RTD/src/Flexio_Pwm_Ip_Irq.o \
./RTD/src/Flexio_Spi_Ip.o \
./RTD/src/Flexio_Spi_Ip_Irq.o \
./RTD/src/Fls.o \
./RTD/src/Fls_IPW.o \
./RTD/src/Ftfc_Fls_Ip.o \
./RTD/src/Ftfc_Fls_Ip_Ac.o \
./RTD/src/Ftm_Gpt_Ip.o \
./RTD/src/Ftm_Icu_Ip.o \
./RTD/src/Ftm_Icu_Ip_Irq.o \
./RTD/src/Ftm_Mcl_Ip.o \
./RTD/src/Ftm_Pwm_Ip.o \
./RTD/src/Ftm_Pwm_Ip_Irq.o \
./RTD/src/Gpio_Dio_Ip.o \
./RTD/src/Gpt.o \
./RTD/src/Gpt_Ipw.o \
./RTD/src/Icu.o \
./RTD/src/Icu_Ipw.o \
./RTD/src/IntCtrl_Ip.o \
./RTD/src/LPit_Gpt_Ip.o \
./RTD/src/Lpit_Icu_Ip.o \
./RTD/src/Lpit_Icu_Ip_Irq.o \
./RTD/src/Lpspi_Ip.o \
./RTD/src/Lpspi_Ip_Irq.o \
./RTD/src/Lptmr_Gpt_Ip.o \
./RTD/src/Lptmr_Icu_Ip.o \
./RTD/src/Lptmr_Icu_Ip_Irq.o \
./RTD/src/Mcu.o \
./RTD/src/Mcu_Dem_Wrapper.o \
./RTD/src/Mcu_Ipw.o \
./RTD/src/Mcu_Ipw_Irq.o \
./RTD/src/Mpu_Ip.o \
./RTD/src/OsIf_Interrupts.o \
./RTD/src/OsIf_Timer.o \
./RTD/src/OsIf_Timer_System.o \
./RTD/src/OsIf_Timer_System_Internal_Systick.o \
./RTD/src/Os_counter_api.o \
./RTD/src/Os_multicore.o \
./RTD/src/Platform.o \
./RTD/src/Platform_Ipw.o \
./RTD/src/Port.o \
./RTD/src/Port_Ci_Icu_Ip.o \
./RTD/src/Port_Ci_Icu_Ip_Irq.o \
./RTD/src/Port_Ci_Port_Ip.o \
./RTD/src/Port_Ipw.o \
./RTD/src/Power_Ip.o \
./RTD/src/Power_Ip_CortexM4.o \
./RTD/src/Power_Ip_PMC.o \
./RTD/src/Power_Ip_PMC_Irq.o \
./RTD/src/Power_Ip_Private.o \
./RTD/src/Power_Ip_RCM.o \
./RTD/src/Power_Ip_RCM_Irq.o \
./RTD/src/Power_Ip_SIM.o \
./RTD/src/Power_Ip_SMC.o \
./RTD/src/Pwm.o \
./RTD/src/Pwm_Ipw.o \
./RTD/src/Pwm_Ipw_Notif.o \
./RTD/src/Qspi_Ip.o \
./RTD/src/Qspi_Ip_Controller.o \
./RTD/src/Qspi_Ip_Sfdp.o \
./RTD/src/Ram_Ip.o \
./RTD/src/SRtc_Ip.o \
./RTD/src/SchM_Can.o \
./RTD/src/SchM_Crc.o \
./RTD/src/SchM_Crypto.o \
./RTD/src/SchM_Dio.o \
./RTD/src/SchM_Fls.o \
./RTD/src/SchM_Gpt.o \
./RTD/src/SchM_Icu.o \
./RTD/src/SchM_Mcl.o \
./RTD/src/SchM_Mcu.o \
./RTD/src/SchM_Port.o \
./RTD/src/SchM_Pwm.o \
./RTD/src/SchM_Rm.o \
./RTD/src/SchM_Spi.o \
./RTD/src/SchM_Wdg.o \
./RTD/src/Spi.o \
./RTD/src/Spi_Ipw.o \
./RTD/src/System_Ip.o \
./RTD/src/Trgmux_Ip.o \
./RTD/src/Trgmux_Ip_HwAcc.o \
./RTD/src/WdgIf.o \
./RTD/src/Wdg_43_Instance0.o \
./RTD/src/Wdg_Channel.o \
./RTD/src/Wdg_Ipw.o \
./RTD/src/Wdg_Ipw_Irq.o \
./RTD/src/Wdog_Ip.o 

C_DEPS += \
./RTD/src/CDD_Crc.d \
./RTD/src/CDD_Mcl.d \
./RTD/src/CDD_Mcl_Ipw.d \
./RTD/src/CDD_Rm.d \
./RTD/src/CDD_Rm_Ipw.d \
./RTD/src/Can.d \
./RTD/src/Can_Ipw.d \
./RTD/src/Can_Irq.d \
./RTD/src/Clock_Ip.d \
./RTD/src/Clock_Ip_Data.d \
./RTD/src/Clock_Ip_Divider.d \
./RTD/src/Clock_Ip_DividerTrigger.d \
./RTD/src/Clock_Ip_ExtOsc.d \
./RTD/src/Clock_Ip_FracDiv.d \
./RTD/src/Clock_Ip_Frequency.d \
./RTD/src/Clock_Ip_Gate.d \
./RTD/src/Clock_Ip_IntOsc.d \
./RTD/src/Clock_Ip_Irq.d \
./RTD/src/Clock_Ip_Monitor.d \
./RTD/src/Clock_Ip_Pll.d \
./RTD/src/Clock_Ip_ProgFreqSwitch.d \
./RTD/src/Clock_Ip_Selector.d \
./RTD/src/Clock_Ip_Specific.d \
./RTD/src/Cmp_Ip.d \
./RTD/src/Crc_Ip.d \
./RTD/src/Crc_Ip_Hardware.d \
./RTD/src/Crc_Ip_Lookup_Tables.d \
./RTD/src/Crc_Ip_Software.d \
./RTD/src/CryIf.d \
./RTD/src/Crypto.d \
./RTD/src/Crypto_ASRExtension.d \
./RTD/src/Crypto_Ipw.d \
./RTD/src/Crypto_KeyManagement.d \
./RTD/src/Crypto_Util.d \
./RTD/src/Csec_Ip.d \
./RTD/src/Csec_Ip_Irq.d \
./RTD/src/Det.d \
./RTD/src/Det_stub.d \
./RTD/src/Dio.d \
./RTD/src/Dio_Ipw.d \
./RTD/src/Dma_Ip.d \
./RTD/src/Dma_Ip_Driver_State.d \
./RTD/src/Dma_Ip_Hw_Access.d \
./RTD/src/Dma_Ip_Irq.d \
./RTD/src/Dma_Ip_Multicore.d \
./RTD/src/EcuM.d \
./RTD/src/FlexCAN_Ip.d \
./RTD/src/FlexCAN_Ip_HwAccess.d \
./RTD/src/FlexCAN_Ip_Irq.d \
./RTD/src/Flexio_Mcl_Ip.d \
./RTD/src/Flexio_Mcl_Ip_HwAccess.d \
./RTD/src/Flexio_Mcl_Ip_Irq.d \
./RTD/src/Flexio_Pwm_Ip.d \
./RTD/src/Flexio_Pwm_Ip_Irq.d \
./RTD/src/Flexio_Spi_Ip.d \
./RTD/src/Flexio_Spi_Ip_Irq.d \
./RTD/src/Fls.d \
./RTD/src/Fls_IPW.d \
./RTD/src/Ftfc_Fls_Ip.d \
./RTD/src/Ftfc_Fls_Ip_Ac.d \
./RTD/src/Ftm_Gpt_Ip.d \
./RTD/src/Ftm_Icu_Ip.d \
./RTD/src/Ftm_Icu_Ip_Irq.d \
./RTD/src/Ftm_Mcl_Ip.d \
./RTD/src/Ftm_Pwm_Ip.d \
./RTD/src/Ftm_Pwm_Ip_Irq.d \
./RTD/src/Gpio_Dio_Ip.d \
./RTD/src/Gpt.d \
./RTD/src/Gpt_Ipw.d \
./RTD/src/Icu.d \
./RTD/src/Icu_Ipw.d \
./RTD/src/IntCtrl_Ip.d \
./RTD/src/LPit_Gpt_Ip.d \
./RTD/src/Lpit_Icu_Ip.d \
./RTD/src/Lpit_Icu_Ip_Irq.d \
./RTD/src/Lpspi_Ip.d \
./RTD/src/Lpspi_Ip_Irq.d \
./RTD/src/Lptmr_Gpt_Ip.d \
./RTD/src/Lptmr_Icu_Ip.d \
./RTD/src/Lptmr_Icu_Ip_Irq.d \
./RTD/src/Mcu.d \
./RTD/src/Mcu_Dem_Wrapper.d \
./RTD/src/Mcu_Ipw.d \
./RTD/src/Mcu_Ipw_Irq.d \
./RTD/src/Mpu_Ip.d \
./RTD/src/OsIf_Interrupts.d \
./RTD/src/OsIf_Timer.d \
./RTD/src/OsIf_Timer_System.d \
./RTD/src/OsIf_Timer_System_Internal_Systick.d \
./RTD/src/Os_counter_api.d \
./RTD/src/Os_multicore.d \
./RTD/src/Platform.d \
./RTD/src/Platform_Ipw.d \
./RTD/src/Port.d \
./RTD/src/Port_Ci_Icu_Ip.d \
./RTD/src/Port_Ci_Icu_Ip_Irq.d \
./RTD/src/Port_Ci_Port_Ip.d \
./RTD/src/Port_Ipw.d \
./RTD/src/Power_Ip.d \
./RTD/src/Power_Ip_CortexM4.d \
./RTD/src/Power_Ip_PMC.d \
./RTD/src/Power_Ip_PMC_Irq.d \
./RTD/src/Power_Ip_Private.d \
./RTD/src/Power_Ip_RCM.d \
./RTD/src/Power_Ip_RCM_Irq.d \
./RTD/src/Power_Ip_SIM.d \
./RTD/src/Power_Ip_SMC.d \
./RTD/src/Pwm.d \
./RTD/src/Pwm_Ipw.d \
./RTD/src/Pwm_Ipw_Notif.d \
./RTD/src/Qspi_Ip.d \
./RTD/src/Qspi_Ip_Controller.d \
./RTD/src/Qspi_Ip_Sfdp.d \
./RTD/src/Ram_Ip.d \
./RTD/src/SRtc_Ip.d \
./RTD/src/SchM_Can.d \
./RTD/src/SchM_Crc.d \
./RTD/src/SchM_Crypto.d \
./RTD/src/SchM_Dio.d \
./RTD/src/SchM_Fls.d \
./RTD/src/SchM_Gpt.d \
./RTD/src/SchM_Icu.d \
./RTD/src/SchM_Mcl.d \
./RTD/src/SchM_Mcu.d \
./RTD/src/SchM_Port.d \
./RTD/src/SchM_Pwm.d \
./RTD/src/SchM_Rm.d \
./RTD/src/SchM_Spi.d \
./RTD/src/SchM_Wdg.d \
./RTD/src/Spi.d \
./RTD/src/Spi_Ipw.d \
./RTD/src/System_Ip.d \
./RTD/src/Trgmux_Ip.d \
./RTD/src/Trgmux_Ip_HwAcc.d \
./RTD/src/WdgIf.d \
./RTD/src/Wdg_43_Instance0.d \
./RTD/src/Wdg_Channel.d \
./RTD/src/Wdg_Ipw.d \
./RTD/src/Wdg_Ipw_Irq.d \
./RTD/src/Wdog_Ip.d 


# Each subdirectory must supply rules for building sources it contributes
RTD/src/%.o: ../RTD/src/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Standard S32DS C Compiler'
	arm-none-eabi-gcc "@RTD/src/CDD_Crc.args" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


